language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
- sqlite3 --version
- sqlite3 roster.db < roster.sql
# command to run tests
script: nosetests
